env = XCURSOR_SIZE,24
env = PATH,$HOME/.local/bin:$PATH
env = EDITOR, nvim
env = QT_QPA_PLATFORMTHEME,qt6ct
env = http_proxy, http$proxy
env = https_proxy, http$proxy
env = all_proxy, socks://$ip:7891
env = ftp_proxy, ftp$proxy
env = rsync_proxy, http$proxy
env = no_proxy, "localhost,$ip,localaddress,.localdomain.com"
env = LD_LIBRARY_PATH,/home/paradoxist/Desktop/Projects/ASR_Caption/libs/x64
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = SERVICE, DEEPSEEK
env = MODEL_NAME, deepseek-chat
env = AUDIO_FILE, '/home/paradoxist/Music/The Layte.wav'
