execr-once = hyprlock
execr-once = waybar & fcitx5 & ydotoold & hyprpaper
execr-once = qq & wechat
execr-once = wl-paste -w cliphist store
execr-once = wl-paste -w wl-copy -p
# exec_always /usr/local/Wolfram/Mathematica/14.0/SystemFiles/Links/WSTPServer/wstpserver &
execr-once = parec --file-format=wav /tmp/always_on.wav
execr-once = $env python ~/Desktop/Projects/WakeWord/wakeword.py
execr-once = socket.sh
execr-once = phone_automation.sh
execr-once = hyprctl output create headless
execr-once = wayvnc -o=HEADLESS-2 -L trace 0.0.0.0 5900

exec-once = [workspace name:󰣇 silent] if [ `date -r .daily/text_today.txt +'%F'` != `date +'%F'` ]; then wolframnb ~/Desktop/Projects/Repository/kards/kards.nb; fi
exec-once = [workspace name:󰣇 silent] if [ `date -r /var/log/pacman.log +'%F'` != `date +'%F'` ]; then $te --hold sudo pacman -Syu; fi
exec-once = [workspace special:card silent; fullscreen] kitty kitten icat --scale-up --place 208x54@0x0 --hold .daily/image_today.png
exec-once = [workspace special:log silent] $te clash -d .config/clash
exec-once = [workspace special:log silent] $te journalctl -f
