# Execute your favorite apps at launch
exec-once = waybar & fcitx5 & ydotoold & hyprpaper
exec-once = qq & wechat
exec-once = [workspace name:󰣇 silent] cd .daily; if [ `date -r . +'%F'` != `date +'%F'` ]; then rm *; echo 0 > speak_count; wolframnb ~/Desktop/Projects/ours/Repository/kards/kards.nb; fi
exec-once = [workspace name:󰣇 silent] if [ `date -r /var/log/pacman.log +'%F'` != `date +'%F'` ]; then $te --hold sudo pacman -Syu; fi
exec-once = [workspace special:card silent; fullscreen] kitty kitten icat --scale-up --place 208x54@0x0 --hold .daily/image_today.png
exec-once = [workspace special:log silent] $te clash -d .config/clash
exec-once = [workspace special:log silent] $te journalctl -f
exec-once = wl-paste -pw xclip
exec-once = wl-paste -w wl-copy -p
# exec-once = while true; do xclip -o | wl-copy -p; sleep 1; done
# exec_always /usr/local/Wolfram/Mathematica/14.0/SystemFiles/Links/WSTPServer/wstpserver &
# exec-once = parec --file-format=wav output.wav
exec-once = socket.sh
exec-once = phone_automation.sh
