# Set programs that you use
$te = kitty
$env = source .python/bin/activate; source path.sh;
$sw = [float; group barred; size 960 540]

$ip = 127.0.0.1
$proxy = ://$ip:7890

source = binds.conf
source = envs.conf
source = vars.conf
source = rules.conf
source = execs.conf

source = keys.conf
source = test.conf
