# Move/resize windows with SUPER + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Conservative window operations with left mouse key
bind = SUPER SHIFT, mouse:272, fullscreen
bind = SUPER CTRL, mouse:272, togglefloating
bind = SUPER ALT, mouse:272, pseudo
bind = SUPER SHIFT CTRL, mouse:272, pin
bind = SUPER SHIFT ALT, mouse:272, togglesplit
bind = SUPER CTRL ALT, mouse:272, moveoutofgroup
bind = SUPER SHIFT CTRL ALT, mouse:272, togglegroup

# Non-conservative window operations with right mouse key
bind = SUPER SHIFT, mouse:273, killactive
bind = SUPER CTRL, mouse:273, focusworkspaceoncurrentmonitor, empty
bind = SUPER ALT, mouse:273, togglespecialworkspace, special:scratchpad
bind = SUPER SHIFT CTRL, mouse:273, focusworkspaceoncurrentmonitor, empty
bind = SUPER SHIFT CTRL, mouse:273, focuscurrentorlast, empty
bind = SUPER SHIFT CTRL, mouse:273, movetoworkspace, empty
# Cannot toggle back so we need to implement it with a script later
bind = SUPER SHIFT ALT, mouse:273, movetoworkspacesilent, special:scratchpad
bind = SUPER CTRL ALT, mouse:273, exec, $sw hyprctl activewindow -j > /tmp/info.json; pkill show.sh || $te show.sh

bind = SUPER SHIFT CTRL ALT, mouse:273, swapactiveworkspaces, DP-1 HDMI-A-1

bind = SUPER, mouse:274, exec, focus.sh paste
bind = SUPER SHIFT, mouse:274, exec, focus.sh type
bind = SUPER CTRL, mouse:274, exec, focus.sh open
bind = SUPER ALT, mouse:274, exec, focus.sh generate
bind = SUPER SHIFT ALT, mouse:274, exec, focus.sh execute
bind = SUPER SHIFT CTRL ALT, mouse:274, exec, focus.sh copy

# Scroll through existing workspaces with SUPER + scroll
bind = SUPER, mouse_down, workspace, e-1
bind = SUPER, mouse_up, workspace, e+1

# Move active window through existing workspaces with SUPER + SHIFT + scroll
bind = SUPER SHIFT, mouse_down, movetoworkspace, e-1
bind = SUPER SHIFT, mouse_up, movetoworkspace, e+1

# Scroll through windows within monitor/group with SUPER + CTRL/ALT + scroll
bind = SUPER CTRL, mouse_down, cyclenext, prev
bind = SUPER CTRL, mouse_up, cyclenext
bind = SUPER ALT, mouse_down, changegroupactive, b
bind = SUPER ALT, mouse_up, changegroupactive, f

# Move window through windows within active monitor/group with SUPER + SHIFT + CTRL/ALT + scroll
bind = SUPER SHIFT CTRL, mouse_down, swapnext, prev
bind = SUPER SHIFT CTRL, mouse_up, swapnext
bind = SUPER SHIFT ALT, mouse_down, movegroupwindow, b
bind = SUPER SHIFT ALT, mouse_up, movegroupwindow, f
