# Move/resize windows with SUPER + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Conservative window operations with left mouse key
bindd = SUPER SHIFT, mouse:272, toggle fullscreen, fullscreen
bindd = SUPER CTRL, mouse:272, toggle floating, togglefloating
bindd = SUPER ALT, mouse:272, toggle pseudo, pseudo
bindd = SUPER SHIFT CTRL, mouse:272, pin window, pin
bindd = SUPER SHIFT ALT, mouse:272, toggle split, togglesplit
bindd = SUPER CTRL ALT, mouse:272, move out of group, moveoutofgroup
bindd = SUPER SHIFT CTRL ALT, mouse:272, toggle group, togglegroup

# Non-conservative window operations with right mouse key
bindd = SUPER SHIFT, mouse:273, kill active window, killactive
bindd = SUPER CTRL, mouse:273, focus empty, focusworkspaceoncurrentmonitor, empty
bindd = SUPER ALT, mouse:273, toggle scratchpad, togglespecialworkspace, scratchpad
bindd = SUPER SHIFT CTRL, mouse:273, move to empty step 1, focusworkspaceoncurrentmonitor, empty
bindd = SUPER SHIFT CTRL, mouse:273, move to empty step 2, focuscurrentorlast, empty
bindd = SUPER SHIFT CTRL, mouse:273, move to empty step 3, movetoworkspace, empty
# Cannot toggle back so we need to implement it with a script later
bindd = SUPER SHIFT ALT, mouse:273, move to scratchpad, movetoworkspacesilent, special:scratchpad
bindd = SUPER CTRL ALT, mouse:273, toggle window info, exec, $sw hyprctl activewindow -j > /tmp/info.json; pkill show.sh || $te show.sh

bindd = SUPER SHIFT CTRL ALT, mouse:273, swap workspaces, swapactiveworkspaces, DP-3 HDMI-A-1

bindd = SUPER, mouse:274, paste focused content, exec, focus.sh paste
bindd = SUPER SHIFT, mouse:274, type focused content, exec, focus.sh type
bindd = SUPER CTRL, mouse:274, open focused content, exec, focus.sh open
bindd = SUPER ALT, mouse:274, generate focused content, exec, focus.sh generate
bindd = SUPER SHIFT ALT, mouse:274, execute focused content, exec, focus.sh execute
bindd = SUPER SHIFT CTRL ALT, mouse:274, copy focused content, exec, focus.sh copy

# Scroll through existing workspaces with SUPER + scroll
bindd = SUPER, mouse_down, previous workspace, workspace, e-1
bindd = SUPER, mouse_up, next workspace, workspace, e+1

# Move active window through existing workspaces with SUPER + SHIFT + scroll
bindd = SUPER SHIFT, mouse_down, move to previous workspace, movetoworkspace, e-1
bindd = SUPER SHIFT, mouse_up, move to next workspace, movetoworkspace, e+1

# Scroll through windows within monitor/group with SUPER + CTRL/ALT + scroll
bindd = SUPER CTRL, mouse_down, previous window, cyclenext, prev
bindd = SUPER CTRL, mouse_up, next window, cyclenext
bindd = SUPER ALT, mouse_down, focus backward in group, changegroupactive, b
bindd = SUPER ALT, mouse_up, focus forward in group, changegroupactive, f

# Move window through windows within active monitor/group with SUPER + SHIFT + CTRL/ALT + scroll
bindd = SUPER SHIFT CTRL, mouse_down, swap with previous window, swapnext, prev
bindd = SUPER SHIFT CTRL, mouse_up, swap with next window, swapnext
bindd = SUPER SHIFT ALT, mouse_down, move backward in group, movegroupwindow, b
bindd = SUPER SHIFT ALT, mouse_up, move forward in group, movegroupwindow, f
