# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-3, prefered, auto, 1, mirror, HEADLESS-2
monitor = HDMI-A-1, preferred, auto, 1, mirror, HEADLESS-2
monitor = HEADLESS-2, 1920x1080@60.00, auto, 1

windowrule = pseudo, class:^(fcitx)$
windowrule = float, title:^(Meeting)$
windowrule = float, title:^(ASRCaption)$
windowrule = float, class:^(hyprland-share-picker)$
windowrule = pseudo, class:^(hyprland-share-picker)$

windowrule = suppressevent maximize, class:.*
windowrule = float, class:^(com.wolfram.Wolfram.14.1)$, title:^(WolframNB)$
windowrule = group barred, class:^(com.wolfram.Wolfram.14.1)$, title:^(WolframNB)$
windowrule = group barred, class:^(wechat)$, title:^(朋友圈)$

windowrule = workspace name:🖧, class:^(scrcpy|Waydroid|org.remmina.Remmina|Gnome-boxes|sunloginclient)$
windowrule = workspace name:󰍡, class:^(QQ|wechat|Feishu|wemeetapp)$
windowrule = workspace name:󰣇, class:^(com.wolfram.Wolfram.14.1)$, title:^(kards.nb - Wolfram)$
windowrule = workspace special:󰬯, class:^(crystal-board)$

workspace = name:, monitor:HEADLESS-2, default:true
