# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = , prefered, auto, 1
monitor = , prefered, auto-down, 1

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = pseudo, fcitx
windowrule = float, Meeting
windowrule = pseudo, hyprland-share-picker
windowrule = float, hyprland-share-picker
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = float, class:^(com.wolfram.Wolfram.14.1)$, title:^(WolframNB)$
windowrulev2 = group barred, class:^(com.wolfram.Wolfram.14.1)$, title:^(WolframNB)$

windowrule = workspace name:🖧, scrcpy
windowrule = workspace name:🖧, Waydroid
windowrule = workspace name:🖧, org.remmina.Remmina
windowrule = workspace name:🖧, Gnome-boxes
windowrule = workspace name:🖧, sunloginclient
windowrule = workspace name:󰍡, QQ
windowrule = workspace name:󰍡, wechat
windowrule = workspace name:󰍡, Feishu
windowrule = workspace name:󰍡, wemeetapp

workspace = name:, monitor:DP-1, default:true
workspace = name:󰍹, monitor:HDMI-A-1, default:true
