# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-3, prefered, auto, 1, mirror, HEADLESS-2
monitor = HDMI-A-1, preferred, auto, 1, mirror, HEADLESS-2
monitor = HEADLESS-2, 1920x1080@60.00, auto, 1

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = pseudo, fcitx
windowrule = float, Meeting
windowrule = pseudo, hyprland-share-picker
windowrule = float, hyprland-share-picker
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = float, class:^(com.wolfram.Wolfram.14.1)$, title:^(WolframNB)$
windowrulev2 = group barred, class:^(com.wolfram.Wolfram.14.1)$, title:^(WolframNB)$
windowrulev2 = group barred, class:^(wechat)$, title:^(朋友圈)$

windowrule = workspace name:🖧, scrcpy
windowrule = workspace name:🖧, Waydroid
windowrule = workspace name:🖧, org.remmina.Remmina
windowrule = workspace name:🖧, Gnome-boxes
windowrule = workspace name:🖧, sunloginclient
windowrule = workspace name:󰍡, QQ
windowrule = workspace name:󰍡, wechat
windowrule = workspace name:󰍡, Feishu
windowrule = workspace name:󰍡, wemeetapp
windowrulev2 = workspace name:󰣇, class:^(com.wolfram.Wolfram.14.1)$, title:^(kards.nb - Wolfram)$

workspace = name:, monitor:DP-3, default:true
workspace = name:󰍹, monitor:HDMI-A-1, default:true
