[opener]
wolfram = [
	{ run = 'mathematica "$@"', desc = "Wolfram Open" },
]
euporie = [
    { run = 'euporie-notebook "$@"', block = true, desc = "Euporie Open" }
]

[open]
prepend_rules = [
	{ name = "*.nb", use = "wolfram" },
	{ name = "*.wl", use = "wolfram" },
	{ name = "*.m", use = "wolfram" },
	{ name = "*.ipynb", use = "euporie" },
]

# not implemented yet, should create a lua script
# see https://yazi-rs.github.io/docs/plugins/overview#previewer
# [plugin]
# prepend_previewers = [
# 	{ name = "*.ipynb", run = "euporie-preview" },
# ]
