execr-once = ffplay ~/Music/FO.mp3 -nodisp -autoexit
execr-once = waybar & fcitx5 & ydotoold & hyprpaper
execr-once = unset http_proxy https_proxy all_proxy; qq & wechat & qqmusic
execr-once = wl-paste -w cliphist store
execr-once = wl-paste -w wl-copy -p
# execr-once = /usr/local/Wolfram/Wolfram/14.1/SystemFiles/Links/WSTPServer/wstpserver &
execr-once = pw-record ~/Music/always_on.wav
execr-once = wf-recorder -yf ~/Videos/always_on.mkv -a=`pactl get-default-sink`.monitor -c h264_vaapi
execr-once = $env python ~/Desktop/Projects/WakeWord/wakeword.py
execr-once = solar_progress.py
execr-once = get_vitals.py
execr-once = socket.sh
execr-once = phone_automation.sh
execr-once = hyprctl output create headless
execr-once = hyprctl keyword monitor Virtual-1,disable
execr-once = wayvnc -L trace 0.0.0.0 5900

exec-once = [workspace 󰔊 silent] $te sh -c 'while true; do run_project.sh SenseStream; done'
exec-once = [workspace special: silent] $te --listen-on unix:/tmp/qwen qwen -y
exec-once = [float; pin; size 200 600; move 1700 240] $te watch -n 1 "sqlite3 ~/.log.db \"SELECT (id % 10) AS digit, content FROM speech WHERE id > (SELECT MAX(id) FROM speech) - 10 ORDER BY (id % 10);\""
exec-once = [workspace special:󰋼 silent] $te mihomo -d .config/mihomo
exec-once = [workspace special:󰋼 silent] $te journalctl -f
