# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-3, prefered, auto, 1, mirror, HEADLESS-2
monitor = HDMI-A-1, preferred, auto, 1, mirror, HEADLESS-2
monitor = HEADLESS-2, 1920x1080@60.00, auto, 1

windowrule = pseudo on, match:class ^(fcitx)$
windowrule = float on, match:title ^(Meeting)$
windowrule = float on, match:class ^(hyprland-share-picker)$
windowrule = pseudo on, match:class ^(hyprland-share-picker)$

windowrule = suppress_event maximize, match:class .*
windowrule = float on, match:class ^(com.wolfram.Wolfram.*)$, match:title ^(WolframNB)$
windowrule = group barred, match:class ^(com.wolfram.Wolfram.*)$, match:title ^(WolframNB)$
windowrule = group barred, match:class ^(wechat)$, match:title ^(朋友圈)$
windowrule = pin on, match:class ^(qqmusic)$, match:title ^(歌词)$

windowrule = workspace name:🖧, match:class ^(Gnome-boxes)$
windowrule = workspace name:󰢹, match:class ^(sdl-freerdp3)$
windowrule = workspace name:󰍡, match:class ^(QQ|wechat|Feishu|wemeetapp)$
windowrule = workspace name:, match:class ^(qqmusic)$
windowrule = workspace name:, match:class ^(steam*)$
windowrule = workspace name:, match:class ^(com.wolfram.Wolfram.*)$, match:title ^(kards.nb - Wolfram)$
windowrule = workspace special:󰬯, match:class ^(crystal-board)$

workspace = name:, monitor:HEADLESS-2, default:true
